server:
  port: 8082
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/postandpoll_service
    username: root
    password: Akshay.51mysql
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
  jackson:
    serialization:
      fail-on-empty-beans: false 
  servlet:
    multipart:
      enabled: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: USER-SERVICE
    
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
      
SECRET_KEY: mySecretKey1234
EXP_TIMEOUT: 86400000